import Head from 'next/head'
import { UserBox } from '../components';
import { NavBar } from '../components/common/NavBar';
import { DetailBox } from '../components/profile/DetailBox';

export default function Home() {
  return (
    <>
      <Head>
        <title>Emyr298</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <div className='max-w-screen overflow-x-hidden mt-[52px] p-4 min-h-[calc(100vh-52px)] flex flex-col lg:flex-row lg:justify-evenly items-center'>
          <UserBox />
          <DetailBox />
        </div>
      </main>
    </>
  );
}
